apiVersion: v1
kind: Service
metadata:
  name: pokemon-manager-3-service
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: pokemon-manager-3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokemon-manager-3
  labels:
    app: pokemon-manager-3
    version: 1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pokemon-manager-3
  template:
    metadata:
      labels:
        app: pokemon-manager-3
    spec:
      containers:
      - name: pokemon-manager-3
        image: corvimae/pokemon-manager-3:latest
        ports:
        - containerPort: 3000