apiVersion: v1
kind: Service
metadata:
  name: pokemon-manager-3-service
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: pokemon-manager-3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokemon-manager-3
  labels:
    app: pokemon-manager-3
    version: 1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pokemon-manager-3
  template:
    metadata:
      labels:
        app: pokemon-manager-3
    spec:
      containers:
      - name: pokemon-manager-3
        image: corvimae/pokemon-manager-3:latest
        ports:
        - containerPort: 3000
        env:
          - name: TWITCH_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: pokemon-manager-3-secrets
                key: twitch.clientId     
          - name: SESSION_SECRET
            valueFrom:
              secretKeyRef:
                name: pokemon-manager-3-secrets
                key: session.secret
          - name: TWITCH_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name:  pokemon-manager-3-secrets
                key: twitch.secret
          - name: PG_HOST
            valueFrom:
              secretKeyRef:
                name: pokemon-manager-3-secrets
                key: postgres.host
          - name: PG_PORT
            valueFrom:
              secretKeyRef:
                name: pokemon-manager-3-secrets
                key: postgres.port
          - name: PG_USERNAME
            valueFrom:
              secretKeyRef:
                name: pokemon-manager-3-secrets
                key: postgres.username
          - name: PG_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pokemon-manager-3-secrets
                key: postgres.password
          - name: PG_DATABASE
            valueFrom:
              secretKeyRef:
                name: pokemon-manager-3-secrets
                key: postgres.database